import NavigationBar from "@/app/components/NavigationBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "../redux/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-full min-h-screen mx-auto bg-slate-200">
          <Providers>
            <NavigationBar />
            {children}
          </Providers>
          ;
        </div>
      </body>
    </html>
  );
}
